version: 0.2

phases:
  build:
    commands:
      - echo "Hello"
      - mvn clean package
  post_build:
    commands:
      - echo "Let's see"
      - java -jar target/s3-upload-1.0-SNAPSHOT.jar

artifacts:
  files:
    - target/s3-upload-1.0-SNAPSHOT.jar
